name: CMake

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    BUILD_TYPE: Release

jobs:
    build:
        strategy:
            matrix:
                include:
                -   arch: "amd64"
                    outfile: "boot.iso"

                -   arch: "riscv64"
                    outfile: "Specific/riscv64/Loader/kOS.Specific.riscv64.Loader"

        name: Build
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v3

            -   name: Install dependencies
                run: |
                    sudo apt install xorriso clang grub-common ninja-build mtools lld -y

            -   name: Make build directory
                run: mkdir ${{github.workspace}}/build

            -   name: Configure CMake
                working-directory: ${{github.workspace}}/build
                run: cmake -S .. -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DTARGET_ARCH=${{ matrix.arch }}

            -   name: Build
                working-directory: ${{github.workspace}}/build
                run: ninja build-iso

            -   name: Upload a Build Artifact
                uses: actions/upload-artifact@v3.1.0
                with:
                    name: out-${{ matrix.arch }}
                    path: ${{github.workspace}}/build/${{ matrix.outfile }}
