name: CMake (x86)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86"]

    name: Build
    runs-on: ubuntu-latest
    container:
        image: koperatingsystem/nucleus:main
        credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DTARGET_ARCH=${{ matrix.arch }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target build-iso

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{github.workspace}}/build/boot.iso
