name: CMake (x86)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        arch: ["x86"]

    name: Build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install xorriso clang grub-common ninja-build mtools lld -y

    - name: Make build directory
      run: mkdir ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake -S .. -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DTARGET_ARCH=${{ matrix.arch }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja build-iso

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{github.workspace}}/build/boot.iso
